### ISSUE TITLE
Using vue components in markdown

### ISSUE THREAD

**Issue by gotenxds** [nuxt/markdown#9]
Any way to achieve that?

use case is having dynamic md string data that contains vue components and you want to render at runtime

so, for example, you fetch some JSON data:

```js
const myData = 
{
 name,
description, // this could look like this '#hello, <v-divider> how are you'
}



const rendered = await md.toMarkup(myData.description)
```

**Comment by little3201** [comment]
typescript support ?

**Comment by MrThursby** [comment]
Any progress?
